### PR TITLE
Created a FileDeleteListener that can easily be added in the builder …

### PR DESCRIPTION
**Pull request by stangabogdan**
Created a FileDeleteListener that detects every deletion from the LRU.

Signed-off-by: Bogdan Stanga <bogdydaci@gmail.com>

### CODE REVIEW

**Comment by danikula** [comment]
@stangabogdan Can you explain how can it be useful? I try to keep code as simple as possible. Each new code should resolve concrete problem. Usually cache hasn't any listener. AndroidVideoCache is just cache. So why it should have this listener?

**Comment by danikula** [comment]
I think more preferable way is just check exist file or not. See details [here](https://github.com/danikula/AndroidVideoCache#listen-caching-progress)

**Comment by stangabogdan** [comment]
@danikula it's a way to detect whenever a file is deleted. For example, one can keep track of the cached files in a database so he can update the database whenever a file is cached and using this feature, whenever a file is deleted.

**Comment by stangabogdan** [comment]
@danikula Yes. But what if I want to receive an event when a file is deleted. I cannot check if a file is cached for ever.

**Comment by danikula** [comment]
@stangabogdan Do you know any image loading library which has same functionality?

**Comment by danikula** [comment]
@stangabogdan Have to decline PR due to [KISS](https://en.wikipedia.org/wiki/KISS_principle). I don't think this is really needed. Client's code can use method `isCached` to check cache existence. This call is cheap and quickly. Just use it.

**Pull request closed without merging**
