### PR TITLE
Better offline cache checking, prefetch url to cache and set source compatability

### PR DESCRIPTION
**Pull request by jarrodholliday**
If the cache is completed exit early and don't compare file sizes from the server for true offline cache.
Was running into situations where there was no connectivity, wifi or cellular data, and the library still tries to check the length of the file on the server. If the cache is already marked completed we should exit early and use the cached file.

Since I forgot to make a separate branch for this pull request some of the other stuff I did is in here too.
Added a function to prefetch a url into cache without having to start it up in a VideoView or media player.
Since I'm using Java8 for RetroLambda the library needed source compatibility set since Java8 was throwing errors building it.

### CODE REVIEW

**Comment by elphinkuo** [comment]
I think this modify is excellent, fix my problems well!

And Jarrod, how can i list all the cached file`s initial URL?

**Comment by jarrodholliday** [comment]
@elphinkuo As of right now I'm not sure on how to list all the cached file's URLs. When I get some free time this weekend I'll look into it.

**Comment by elphinkuo** [comment]
Thank you Jarrod

**Comment by moxiaohu** [comment]
Thanks jarrodholliday , this helps a lot!

**Comment by danikula** [comment]
@jarrodholliday thanks for your contribution. It seems [this PR](https://github.com/danikula/AndroidVideoCache/pull/67) resolves same problem with help of same method. But It looks much pretty. Your PR should contain single commit that resolves concrete problem. So have to decline your PR. [This PR](https://github.com/danikula/AndroidVideoCache/pull/67) looks more promising. Sorry. 
If you want to merge you solution please take into account [my comment](https://github.com/danikula/AndroidVideoCache/pull/67#issuecomment-235676866) and make new PR.

Anyway thanks for contribution! 👍

**Comment by jarrodholliday** [comment]
@danikula Yea I screwed up and made the PR off of master and continued to do work. When I get back from vacation I'll take a look at your comment.

**Comment by danikula** [comment]
@jarrodholliday Your [fork](https://github.com/jarrodholliday/AndroidVideoCache/commits/master) contains a lot useful stuff. Hope with your help I'll merge into original repo the best fixes.

**Pull request closed without merging**
