### PR TITLE
Speed up fetching content info by using cache

### PR DESCRIPTION
**Pull request by gbhall**
Improved fetchContentInfo speed for preexisting content by using SQLite database.

This update increases fetchContentInfo()'s speed from ~500ms to 1ms.

### CODE REVIEW

**Comment by danikula** [comment]
@gbhall Thanks for your contribution. :+1:

Your code resolves problem, but should be improved. There are a lot of sql specific code in  `HttpUrlSource `. `HttpUrlSource ` shouldn't contain **any** database logic. The better solution is new `interface ContentInfo` with database based implementation `DatabaseContentInfo`. Also your implementation doesn't contain any test that proof your code works well. 
Please rebase master, implement you pull request in this way, write tests.

Please notify me if you don't want improve your PR. In this case I will implement it by myself. 

Sorry for looooooooong delay on your PR.

**Comment by gbhall** [comment]
Hey man, no problem :)

Sorry I don't currently have any time to improve my PR. However if you have
any questions, feel free to ask me :)

Cheers!
Gareth

**Comment by danikula** [comment]
@gbhall thanks for response. I will get your solution as start point and will improve it as described above.

**Comment by danikula** [comment]
Fixed [here](https://github.com/danikula/AndroidVideoCache/commit/71c6301eb49d37c4aef8d70b8e94b5403d5627cc). @gbhall Thanks for contribution.

**Comment by gbhall** [comment]
No problem man, glad I could help! :)

**Pull request closed without merging**
