### PR TITLE
allow user to create and implement custom DiskCache

### PR DESCRIPTION
**Pull request by jpage4500**
Hi,

I really just wanted to create a pull request for my first commit  - 5248c5c0f9f9783236cf3f091e09fe754dcec61d

I want to define a max cache size but *also* remove any cached files older than X. I ended up creating a simple class that extends LruDiskUsage.

The second commit was just to use the latest build tools which Android Studio was nagging me to do.

Anyway, let me know if any questions

thanks!
joe

### CODE REVIEW

**Comment by danikula** [comment]
@jpage4500 thanks for contribution. Your 2nd commit broke tests. Please remove it and push force to this branch. I will merge your PR.

**Comment by danikula** [comment]
@jpage4500 can you make changes I requested?

**Comment by jpage4500** [comment]
Sorry for the delay. I haven't done many pull requests before so I'll try to figure this out.

**Comment by danikula** [comment]
@jpage4500 if you have any problem with this you can just provide write permission for your repo `jpage4500/AndroidVideoCache` to me and I will help you make changes.

**Comment by jpage4500** [comment]
Hi,

Can you let me know if this looks good? I'm currently using this fork in my app with jitpack.io so I just want to be careful to make sure that continues to work (until the official library has these changes of course)

I do have a second change in here which maybe I should have opened in issue for first.. basically, the accept() logic was never getting called. It turned out that some devices (Samsung Galaxy S5 for one) won't update a file using lastModified(). So, the Exception that was being thrown before was preventing the accept() method from getting called. I'm just printing out a warning in the log instead for now (feel free to remove that if you want though)

**Comment by danikula** [comment]
@jpage4500 please collapse all your 5 commits to single commit.

**Comment by danikula** [comment]
@jpage4500 please provide write access for me to your [fork](https://github.com/jpage4500/AndroidVideoCache). I want to improve your PR little bit.

**Comment by jpage4500** [comment]
Hi @danikula - sorry I haven't looked at this in a while but I am using my forked version (via jitpack.io) in our app. But, of course I'd love to go to the official version as long as there's some way to handle that custom delete logic.

Feel free to modify or even just copy/paste anything into your source if the pull request doesn't work.

**Comment by danikula** [comment]
@jpage4500  Despite this PR looks as declined [your commit](https://github.com/danikula/AndroidVideoCache/commit/f5dd92efffe482e33ae39cc67c33df7146277b43) (little bit edited by me) is in master. Thanks for contributing. It will be available in `2.7.0`

**Comment by jpage4500** [comment]
just got around to moving from my fork to the official version 2.7.0 - looks great thanks!

if anyone's interested here's my custom disk cache.. basically the video's in the app I'm working on aren't needed the next day so my custom cache logic is to remove anything > 1 day or 100 Meg total size.

```
    private static HttpProxyCacheServer newProxy() {
        HttpProxyCacheServer.Builder builder = new HttpProxyCacheServer.Builder(FanEngine.getContext());
        builder.diskUsage(new SizeAndDateDiskUsage());
        return builder.build();
    }

    /**
     * Allow video cache to grow up 100 Meg
     * Also, delete videos that are older than 1 day
     */
    private static class SizeAndDateDiskUsage extends LruDiskUsage {
        // max chache (in Meg)
        private static final int MAX_CACHE = 100 * 1024 * 1024;
        // max age to keep files (in ms)
        private static final int MAX_AGE_MS = 24 * Constants.MILISECONDS_PER_HOUR;

        @Override
        protected boolean accept(File file, long totalSize, int totalCount) {
            boolean keepFile = totalSize <= MAX_CACHE;
            long ageMs = 0;
            if (keepFile) {
                ageMs = System.currentTimeMillis() - file.lastModified();
                keepFile = (ageMs <= MAX_AGE_MS);
            }

            if (!keepFile) {
                log.trace("removing: size:{}, count:{}, age:{}ms, {}", totalSize, totalCount, ageMs, file.getAbsolutePath());
            }
            return keepFile;
        }
    }
```

**Pull request closed without merging**
