### PR TITLE
Support redirection

### PR DESCRIPTION
**Pull request by ongakuer**
Fix bug #11

### CODE REVIEW

**Comment by danikula** [comment]
@ongakuer please add unit test for this case

**Comment by ongakuer** [comment]
Sorry , I can`t make multi redirect url with short link…

**Comment by danikula** [comment]
But you can make short link on short link

**Comment by ongakuer** [comment]
Yes,I've tried. But short link server can analyze the redirect url , and just shorter the final link…

**Comment by danikula** [comment]
Use [bit.ly](https://bitly.com) and [ow.ly](http://ow.ly/) and make short link on each other. They doesn't recognize each other.

**Comment by ongakuer** [comment]
I think something wrong with short url or HttpURLConnection.  For the first time the short url response code was 301, and next time response code was 200

**Comment by danikula** [comment]
@ongakuer I merged your PR to master. Thanks for your contribution to project. 

> I think something wrong with short url or HttpURLConnection. For the first time the short url response code was 301, and next time response code was 200

It is not bug `HttpURLConnection` uses cache.

**Comment by ltpquang** [comment]
@ongakuer why didn't you handle the code `307 Temporary Redirect`? Is there any specific reason or you just simply missed it? My app is broken because the server side changes the redirecting code from `302` to `307`

**Pull request merged**
